---
baseURL: https://www.vins-drach.fr/
languageCode: fr-fr
title: Vins Drach
theme:
- vinsdrach
DefaultContentLanguage: fr
menu:
  "main:
  - identifier: about
    name: Où trouver les vins
    title: Où trouver les vins
    url: /pointsdevente
    weight: -110"
SectionPagesMenu: ""
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: true
canonifyURLs: true
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
params:
  favicon: "/images/favicondrach2.png"
  site_logo: images/logorouge-sansfond-85px.png
  description: The last theme you'll ever need. Maybe.
  facebook: https://www.facebook.com/Les-Vins-Drach-100855508872281
  twitter: ''
  instagram: https://www.instagram.com/vins_drach/
  youtube: ''
  github: ''
  gitlab: ''
  linkedin: ''
  mastodon: ''
  slack: ''
  stackoverflow: ''
  rss: ''
  background_color_class: bg-black
  cover_dimming_class: bg-white-20
  featured_image: "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number: 2
